export const resources = {
  en: {
    translation: {
      // Authentication
      "auth.login.title": "Sign in to your account",
      "auth.register.title": "Create your account",
      "auth.forgot.title": "Reset your password",
      "auth.email": "Email address",
      "auth.password": "Password",
      "auth.confirmPassword": "Confirm password",
      "auth.login.button": "Sign in",
      "auth.register.button": "Create account",
      "auth.forgot.button": "Send reset instructions",
      "auth.loading": "Please wait...",
      "auth.or": "Or",
      "auth.forgotPassword": "Forgot your password?",
      "auth.createAccount": "Create an account",
      "auth.alreadyHaveAccount": "Already have an account?",
      "auth.backToLogin": "Back to login",
      "auth.errors.invalidEmail": "Invalid email address",
      "auth.errors.passwordMismatch": "Passwords do not match",
      "auth.errors.passwordLength": "Password must be at least 8 characters",
      "auth.errors.generic": "An error occurred. Please try again.",
      "auth.success.resetSent": "Password reset instructions sent to your email",
      "auth.success.registered": "Registration successful! Please check your email.",
      
      // Navbar
      "nav.home": "Home",
      "nav.services": "Services",
      "nav.pricing": "Pricing",
      "nav.about": "About",
      "nav.contact": "Contact",
      "nav.login": "Login",
      "nav.getStarted": "Get Started",
      
      // Hero Section
      "hero.title": "Digital Growth Powered by AI",
      "hero.subtitle": "Collective intelligence serving your digital growth",
      "hero.description": "Eidynia is a next-generation digital agency that combines AI automation with human expertise to deliver exceptional digital services for entrepreneurs and growing businesses.",
      "hero.cta.primary": "Discover Our Services",
      "hero.cta.secondary": "Book a Demo",
      
      // Services Section
      "services.title": "Our AI-Powered Services",
      "services.subtitle": "Everything you need to grow digitally",
      "services.web.title": "Website Creation",
      "services.web.description": "Beautiful, responsive websites generated by AI and refined by experts, all without code.",
      "services.seo.title": "SEO Content Generation",
      "services.seo.description": "High-quality, SEO-optimized content automatically generated to boost your organic visibility.",
      "services.branding.title": "AI Branding",
      "services.branding.description": "Professional logos, color schemes, and visual identity created with AI assistance.",
      "services.marketing.title": "Automated Marketing",
      "services.marketing.description": "Email campaigns, social media content, and marketing strategies powered by AI.",
      "services.crm.title": "Smart CRM",
      "services.crm.description": "AI-enhanced customer relationship management to identify opportunities and build loyalty.",
      
      // How It Works
      "how.title": "How Eidynia Works",
      "how.subtitle": "Seamless process from idea to execution",
      "how.step1.title": "1. Brief Creation",
      "how.step1.description": "Share your needs and goals through our smart AI questionnaire.",
      "how.step2.title": "2. AI Generation",
      "how.step2.description": "Our AI creates initial designs, content, and strategies based on your requirements.",
      "how.step3.title": "3. Expert Review",
      "how.step3.description": "Our remote team of experts reviews and refines the AI-generated output.",
      "how.step4.title": "4. Delivery & Iteration",
      "how.step4.description": "Receive your deliverables and request adjustments through your client portal.",
      
      // Pricing
      "pricing.title": "Transparent Pricing",
      "pricing.subtitle": "Plans that scale with your business",
      "pricing.starter.title": "Starter",
      "pricing.starter.price": "€99",
      "pricing.starter.period": "/month",
      "pricing.starter.description": "Perfect for new entrepreneurs",
      "pricing.growth.title": "Growth",
      "pricing.growth.price": "€249",
      "pricing.growth.period": "/month",
      "pricing.growth.description": "For businesses ready to expand",
      "pricing.scale.title": "Scale",
      "pricing.scale.price": "€499",
      "pricing.scale.period": "/month",
      "pricing.scale.description": "Enterprise-level digital solutions",
      "pricing.custom.title": "Custom",
      "pricing.custom.description": "Tailored solutions for specific needs",
      "pricing.cta": "Get Started",
      
      // Testimonials
      "testimonials.title": "Client Success Stories",
      "testimonials.subtitle": "See what our clients have achieved",
      
      // CTA Section
      "cta.title": "Ready to Transform Your Digital Presence?",
      "cta.description": "Join the hundreds of businesses already growing with Eidynia.",
      "cta.button": "Start Your Journey",
      
      // Footer
      "footer.rights": "All rights reserved",
      "footer.privacy": "Privacy Policy",
      "footer.terms": "Terms of Service",
    }
  },
  fr: {
    translation: {
      // Authentication
      "auth.login.title": "Connexion",
      "auth.register.title": "Créer un compte",
      "auth.forgot.title": "Réinitialiser votre mot de passe",
      "auth.email": "Adresse email",
      "auth.password": "Mot de passe",
      "auth.confirmPassword": "Confirmer le mot de passe",
      "auth.login.button": "Se connecter",
      "auth.register.button": "Créer un compte",
      "auth.forgot.button": "Envoyer les instructions",
      "auth.loading": "Veuillez patienter...",
      "auth.or": "Ou",
      "auth.forgotPassword": "Mot de passe oublié ?",
      "auth.createAccount": "Créer un compte",
      "auth.alreadyHaveAccount": "Déjà un compte ?",
      "auth.backToLogin": "Retour à la connexion",
      "auth.errors.invalidEmail": "Adresse email invalide",
      "auth.errors.passwordMismatch": "Les mots de passe ne correspondent pas",
      "auth.errors.passwordLength": "Le mot de passe doit contenir au moins 8 caractères",
      "auth.errors.generic": "Une erreur est survenue. Veuillez réessayer.",
      "auth.success.resetSent": "Instructions de réinitialisation envoyées par email",
      "auth.success.registered": "Inscription réussie ! Vérifiez votre email.",
      
      // Navbar
      "nav.home": "Accueil",
      "nav.services": "Services",
      "nav.pricing": "Tarifs",
      "nav.about": "À propos",
      "nav.contact": "Contact",
      "nav.login": "Connexion",
      "nav.getStarted": "Commencer",
      
      // Hero Section
      "hero.title": "Croissance Digitale Propulsée par l'IA",
      "hero.subtitle": "L'intelligence collective au service de votre croissance digitale",
      "hero.description": "Eidynia est une agence digitale nouvelle génération qui combine l'automatisation IA avec l'expertise humaine pour offrir des services digitaux exceptionnels aux entrepreneurs et entreprises en croissance.",
      "hero.cta.primary": "Découvrir Nos Services",
      "hero.cta.secondary": "Réserver une Démo",
      
      // Services Section
      "services.title": "Nos Services Propulsés par l'IA",
      "services.subtitle": "Tout ce dont vous avez besoin pour votre croissance digitale",
      "services.web.title": "Création de Sites Web",
      "services.web.description": "Sites web magnifiques et responsifs générés par IA et affinés par des experts, sans code.",
      "services.seo.title": "Génération de Contenu SEO",
      "services.seo.description": "Contenu de haute qualité, optimisé pour le référencement, généré automatiquement pour booster votre visibilité.",
      "services.branding.title": "Branding IA",
      "services.branding.description": "Logos professionnels, palettes de couleurs et identité visuelle créés avec l'assistance de l'IA.",
      "services.marketing.title": "Marketing Automatisé",
      "services.marketing.description": "Campagnes email, contenu pour réseaux sociaux et stratégies marketing propulsées par l'IA.",
      "services.crm.title": "CRM Intelligent",
      "services.crm.description": "Gestion de la relation client améliorée par l'IA pour identifier les opportunités et fidéliser.",
      
      // How It Works
      "how.title": "Comment Fonctionne Eidynia",
      "how.subtitle": "Processus fluide de l'idée à l'exécution",
      "how.step1.title": "1. Création du Brief",
      "how.step1.description": "Partagez vos besoins et objectifs via notre questionnaire IA intelligent.",
      "how.step2.title": "2. Génération par IA",
      "how.step2.description": "Notre IA crée les designs initiaux, le contenu et les stratégies selon vos exigences.",
      "how.step3.title": "3. Révision par Experts",
      "how.step3.description": "Notre équipe d'experts à distance révise et affine les résultats générés par l'IA.",
      "how.step4.title": "4. Livraison & Itération",
      "how.step4.description": "Recevez vos livrables et demandez des ajustements via votre portail client.",
      
      // Pricing
      "pricing.title": "Tarification Transparente",
      "pricing.subtitle": "Des forfaits qui évoluent avec votre entreprise",
      "pricing.starter.title": "Débutant",
      "pricing.starter.price": "99€",
      "pricing.starter.period": "/mois",
      "pricing.starter.description": "Parfait pour les nouveaux entrepreneurs",
      "pricing.growth.title": "Croissance",
      "pricing.growth.price": "249€",
      "pricing.growth.period": "/mois",
      "pricing.growth.description": "Pour les entreprises prêtes à se développer",
      "pricing.scale.title": "Expansion",
      "pricing.scale.price": "499€",
      "pricing.scale.period": "/mois",
      "pricing.scale.description": "Solutions digitales niveau entreprise",
      "pricing.custom.title": "Personnalisé",
      "pricing.custom.description": "Solutions sur mesure pour besoins spécifiques",
      "pricing.cta": "Commencer",
      
      // Testimonials
      "testimonials.title": "Réussites de Nos Clients",
      "testimonials.subtitle": "Découvrez ce que nos clients ont accompli",
      
      // CTA Section
      "cta.title": "Prêt à Transformer Votre Présence Digitale ?",
      "cta.description": "Rejoignez les centaines d'entreprises qui se développent déjà avec Eidynia.",
      "cta.button": "Commencer Votre Parcours",
      
      // Footer
      "footer.rights": "Tous droits réservés",
      "footer.privacy": "Politique de Confidentialité",
      "footer.terms": "Conditions d'Utilisation",
    }
  }
};