import React from 'react';
import { useTranslation } from 'react-i18next';
import { motion } from 'framer-motion';

import { 
  Globe, 
  Search, 
  Palette, 
  BarChart, 
  UsersRound,
  Zap,
  ArrowRight
} from 'lucide-react';
import ServiceCard from '../components/services/ServiceCard';

const ServicesPage: React.FC = () => {
  const { t } = useTranslation();

  const services = [
    {
      icon: <Globe className="h-8 w-8 text-white" />,
      title: "Website Creation",
      description: "Beautiful, responsive websites generated by AI and refined by experts, all without code.",
      features: [
        "AI-powered design suggestions",
        "Responsive layouts for all devices",
        "SEO optimization built-in",
        "Custom domain integration",
        "Analytics dashboard"
      ],
      color: "bg-primary-600 dark:bg-primary-500"
    },
    {
      icon: <Search className="h-8 w-8 text-white" />,
      title: "SEO Content Generation",
      description: "High-quality, SEO-optimized content automatically generated to boost your organic visibility.",
      features: [
        "Keyword research and analysis",
        "Content strategy planning",
        "Blog post generation",
        "Meta description optimization",
        "Performance tracking"
      ],
      color: "bg-secondary-600 dark:bg-secondary-500"
    },
    {
      icon: <Palette className="h-8 w-8 text-white" />,
      title: "AI Branding",
      description: "Professional logos, color schemes, and visual identity created with AI assistance.",
      features: [
        "Logo design with AI",
        "Brand color palette",
        "Typography selection",
        "Brand guidelines",
        "Social media templates"
      ],
      color: "bg-accent-600 dark:bg-accent-500"
    },
    {
      icon: <BarChart className="h-8 w-8 text-white" />,
      title: "Automated Marketing",
      description: "Email campaigns, social media content, and marketing strategies powered by AI.",
      features: [
        "Email campaign automation",
        "Social media scheduling",
        "Content calendar",
        "Performance analytics",
        "A/B testing"
      ],
      color: "bg-success-600 dark:bg-success-500"
    },
    {
      icon: <UsersRound className="h-8 w-8 text-white" />,
      title: "Smart CRM",
      description: "AI-enhanced customer relationship management to identify opportunities and build loyalty.",
      features: [
        "Contact management",
        "Lead scoring",
        "Task automation",
        "Customer insights",
        "Integration capabilities"
      ],
      color: "bg-warning-600 dark:bg-warning-500"
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Hero Section */}
      <section className="relative py-20 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary-600/20 to-secondary-600/20 dark:from-primary-900/20 dark:to-secondary-900/20" />
        <div className="container mx-auto px-4 relative">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center max-w-3xl mx-auto"
          >
            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-6">
              AI-Powered Digital Services for Your Growth
            </h1>
            <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
              Transform your digital presence with our suite of AI-enhanced services, designed to help your business thrive in the digital age.
            </p>
            <div className="flex items-center justify-center space-x-4">
              <a
                href="#services"
                className="px-8 py-3 text-base font-medium text-white bg-gradient-to-r from-primary-600 to-secondary-600 hover:from-primary-700 hover:to-secondary-700 rounded-md shadow-sm transition-all hover:shadow-md flex items-center"
              >
                Explore Services
                <ArrowRight className="ml-2 h-5 w-5" />
              </a>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Services Grid */}
      <section id="services" className="py-20">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {services.map((service, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
              >
                <ServiceCard
                  icon={service.icon}
                  title={service.title}
                  description={service.description}
                  features={service.features}
                  color={service.color}
                />
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-br from-primary-600 to-secondary-600 dark:from-primary-900 dark:to-secondary-900">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
              Ready to Transform Your Digital Presence?
            </h2>
            <p className="text-xl text-white/90 mb-8">
              Join hundreds of businesses already growing with our AI-powered solutions.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-4">
              <a
                href="/contact"
                className="px-8 py-3 text-base font-medium text-primary-600 bg-white hover:bg-gray-50 rounded-md shadow-sm transition-all hover:shadow-md w-full sm:w-auto"
              >
                Contact Us
              </a>
              <a
                href="/pricing"
                className="px-8 py-3 text-base font-medium text-white border-2 border-white hover:bg-white/10 rounded-md transition-all w-full sm:w-auto"
              >
                View Pricing
              </a>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default ServicesPage;